import React,{useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import VideoWhiteboard from '../src/components/video/VideoWhiteboard';
import VideoPresentation from '../src/components/video/VideoPresentation';
import VideoTimeline from '../src/components/video/VideoTimeline';
import '../src/styles/lesson-video-workflow.css';
if(!import.meta.env.DEV)throw Error('Development verification only');
function Tools(){const preview=useRef(null),annotation=useRef(null),player=useRef(null),[frame,setFrame]=useState(''),[url,setUrl]=useState(''),[range,setRange]=useState([0,12]),[capturing,setCapturing]=useState(false);
function draw(canvas){if(!canvas)return;annotation.current=canvas;const out=preview.current;out.width=canvas.width;out.height=canvas.height;const ctx=out.getContext('2d');ctx.fillStyle='#173447';ctx.fillRect(0,0,out.width,out.height);ctx.fillStyle='white';ctx.font='40px Arial';ctx.fillText('Synthetic shared screen',60,110);ctx.drawImage(canvas,0,0);setFrame(`${canvas.width} × ${canvas.height}`);}
return <main className="video-workflow video-workflow-recording" style={{margin:'20px auto',fontFamily:'Arial',padding:16}}><h1>Video tools verification</h1><p role="status">Exported frame: {frame}</p><div className="video-record-workspace"><section className="video-live-preview"><h2>Live video preview</h2><p>Synthetic screen source • no device access</p><div className="video-stage"><canvas ref={preview}/></div></section><div><VideoWhiteboard sceneId="qa-screen-annotation-whiteboard" language="en" overlay={true} onFrame={draw}/></div></div><VideoPresentation storageKey="qa-video-library-presentation" language="en" onFrame={draw}/><p role="status">{capturing?'Recording annotation verification':'Ready'}</p><button disabled={capturing} onClick={async()=>{setCapturing(true);const canvas=document.createElement('canvas');canvas.width=640;canvas.height=360;const ctx=canvas.getContext('2d'),stream=canvas.captureStream(30),audio=new AudioContext(),destination=audio.createMediaStreamDestination(),tone=audio.createOscillator(),gain=audio.createGain();gain.gain.value=.04;tone.connect(gain).connect(destination);tone.start();await audio.resume();destination.stream.getAudioTracks().forEach(track=>stream.addTrack(track));const recorder=new MediaRecorder(stream),chunks=[];const done=new Promise(resolve=>{recorder.ondataavailable=event=>chunks.push(event.data);recorder.onstop=resolve;});let tick;function paint(){ctx.fillStyle='#173447';ctx.fillRect(0,0,640,360);ctx.fillStyle='white';ctx.font='32px Arial';ctx.fillText('Synthetic screen '+performance.now().toFixed(0),20,60);if(annotation.current)ctx.drawImage(annotation.current,0,0,640,360);tick=requestAnimationFrame(paint);}paint();recorder.start(250);setTimeout(()=>recorder.stop(),12000);await done;cancelAnimationFrame(tick);stream.getTracks().forEach(track=>track.stop());tone.stop();await audio.close();setCapturing(false);setUrl(URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType})));}}>Generate real video for timeline</button><video ref={player} controls src={url||undefined} style={{width:480}}/>{url&&<VideoTimeline url={url} videoRef={player} duration={12} start={range[0]} end={range[1]} onRange={(a,b)=>setRange([a,b])} language="en"/>}<p>Selection: {range.join(' — ')}</p></main>}
createRoot(document.getElementById('root')).render(<Tools/>);
