import React,{useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import VideoWhiteboard from '../src/components/video/VideoWhiteboard';
import VideoPresentation from '../src/components/video/VideoPresentation';
import VideoTimeline from '../src/components/video/VideoTimeline';
import '../src/styles/lesson-video-workflow.css';
if(!import.meta.env.DEV)throw Error('Development verification only');
function Tools(){const preview=useRef(null),player=useRef(null),[frame,setFrame]=useState(''),[url,setUrl]=useState(''),[range,setRange]=useState([0,4]);
function draw(canvas){if(!canvas)return;const out=preview.current;out.width=canvas.width;out.height=canvas.height;out.getContext('2d').drawImage(canvas,0,0);setFrame(`${canvas.width} × ${canvas.height}`);}
return <main className="video-workflow" style={{margin:'20px auto',fontFamily:'Arial',padding:16}}><h1>Video tools verification</h1><p role="status">Exported frame: {frame}</p><canvas ref={preview} style={{width:480,maxWidth:'100%',background:'#edf0f2',border:'1px solid #aaa'}}/><VideoWhiteboard sceneId="qa-video-library-whiteboard" language="en" onFrame={draw}/><VideoPresentation storageKey="qa-video-library-presentation" language="en" onFrame={draw}/><button onClick={async()=>{const canvas=document.createElement('canvas');canvas.width=640;canvas.height=360;const ctx=canvas.getContext('2d'),stream=canvas.captureStream(30),audio=new AudioContext(),destination=audio.createMediaStreamDestination(),tone=audio.createOscillator(),gain=audio.createGain();gain.gain.value=.04;tone.connect(gain).connect(destination);tone.start();await audio.resume();destination.stream.getAudioTracks().forEach(track=>stream.addTrack(track));const recorder=new MediaRecorder(stream),chunks=[];const done=new Promise(resolve=>{recorder.ondataavailable=event=>chunks.push(event.data);recorder.onstop=resolve;});let tick;function paint(){ctx.fillStyle='#173447';ctx.fillRect(0,0,640,360);ctx.fillStyle='white';ctx.font='32px Arial';ctx.fillText('Real timeline test '+performance.now().toFixed(0),20,180);tick=requestAnimationFrame(paint);}paint();recorder.start(250);setTimeout(()=>recorder.stop(),4000);await done;cancelAnimationFrame(tick);stream.getTracks().forEach(track=>track.stop());tone.stop();await audio.close();setUrl(URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType})));}}>Generate real video for timeline</button><video ref={player} controls src={url||undefined} style={{width:480}}/>{url&&<VideoTimeline url={url} videoRef={player} duration={4} start={range[0]} end={range[1]} onRange={(a,b)=>setRange([a,b])} language="en"/>}<p>Selection: {range.join(' — ')}</p></main>}
createRoot(document.getElementById('root')).render(<Tools/>);
