import { useEffect,useRef,useState } from 'react';
import { readMedia,saveMedia } from '../../services/mediaStore';
import pdfWorker from 'pdfjs-dist/build/pdf.worker.min.mjs?url';

export default function VideoPresentation({ storageKey,language,onFrame,onError }) {
  const [file,setFile]=useState(null),[page,setPage]=useState(1),[pages,setPages]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const doc=useRef(null),frame=useRef(null),latest=useRef({onFrame,onError});latest.current={onFrame,onError};
  const t=(ar,en)=>language==='ar'?ar:en;
  async function open(blob,name){setBusy(true);setError('');doc.current?.destroy();doc.current=null;try{
    if(/\.(pptx?|docx?)$/i.test(name)){setFile({name,type:'office'});setPages(0);latest.current.onFrame(null);return;}
    if(blob.type==='application/pdf'||/\.pdf$/i.test(name)){const pdf=await import('pdfjs-dist');pdf.GlobalWorkerOptions.workerSrc=pdfWorker;doc.current=await pdf.getDocument({data:new Uint8Array(await blob.arrayBuffer()),isEvalSupported:false}).promise;setPages(doc.current.numPages);setPage(1);setFile({name,type:'pdf'});}
    else{const image=await createImageBitmap(blob);const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;canvas.getContext('2d').drawImage(image,0,0);image.close();frame.current=canvas;latest.current.onFrame(canvas);setFile({name,type:'image'});setPages(1);setPage(1);}
  }catch{setError(t('تعذّر عرض الملف. جرّب PDF غير محمي أو صورة.','Unable to display the file. Try an unprotected PDF or image.'));}finally{setBusy(false);}}
  useEffect(()=>{let cancelled=false;async function restore(){try{const id=localStorage.getItem(storageKey),saved=await readMedia(id);if(!cancelled&&saved)await open(saved.blob,saved.name);}catch{/* User can choose another file. */}}restore();return()=>{cancelled=true;doc.current?.destroy();};},[storageKey]);
  useEffect(()=>{if(!doc.current||file?.type!=='pdf')return;let stopped=false,task;const document=doc.current;async function draw(){setBusy(true);try{const pdfPage=await document.getPage(page);if(stopped)return;const natural=pdfPage.getViewport({scale:1}),viewport=pdfPage.getViewport({scale:Math.min(1920/natural.width,1080/natural.height)}),canvas=window.document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);task=pdfPage.render({canvasContext:canvas.getContext('2d'),viewport});await task.promise;if(!stopped){frame.current=canvas;latest.current.onFrame(canvas);}}catch(cause){if(!stopped&&cause.name!=='RenderingCancelledException')setError(t('تعذّر عرض الصفحة.','Unable to render this page.'));}finally{if(!stopped)setBusy(false);}}draw();return()=>{stopped=true;task?.cancel();};},[file,page]);
  return <section className="video-presentation"><h2>{t('مشاركة ملف داخل الفيديو','Present a file inside the video')}</h2><label>{t('PDF / PowerPoint / Word / PNG / JPEG / WebP (25MB)','PDF, PowerPoint, Word or image (25MB)')}<input type="file" accept=".pdf,.ppt,.pptx,.doc,.docx,image/png,image/jpeg,image/webp" disabled={busy} onChange={async event=>{const selected=event.target.files[0];event.target.value='';if(!selected)return;if(!selected.size||selected.size>25*1024**2||!(/\.(pdf|pptx?|docx?)$/i.test(selected.name)||['image/png','image/jpeg','image/webp'].includes(selected.type))){setError(t('اختر PDF أو صورة بحجم أقصى 25MB.','Choose a PDF, PowerPoint, Word or image up to 25MB.'));return;}setBusy(true);try{const saved=await saveMedia(selected,{name:selected.name});localStorage.setItem(storageKey,saved.id);await open(selected,selected.name);}catch{setBusy(false);setError(t('تعذّر حفظ الملف.','Unable to save the file.'));}}}/></label>
    {file&&<div className="video-actions"><strong>{file.name}</strong>{file.type==='pdf'&&<><button type="button" disabled={busy||page<=1} onClick={()=>setPage(value=>value-1)}>{t('الصفحة السابقة','Previous page')}</button><span>{page} / {pages}</span><button type="button" disabled={busy||page>=pages} onClick={()=>setPage(value=>value+1)}>{t('الصفحة التالية','Next page')}</button></>}<button type="button" onClick={()=>{doc.current?.destroy();doc.current=null;setFile(null);latest.current.onFrame(null);localStorage.removeItem(storageKey);}}>{t('إزالة الملف من العرض','Remove presentation')}</button></div>}
    {file?.type==='office'&&<p role="status">{t('تم حفظ الملف. لعرضه الآن، شارك نافذته أو اختر نسخة PDF. العرض المباشر ينتظر ربط خدمة تحويل الملفات.','File saved. Share its window or choose a PDF copy to present it now. Direct presentation awaits the document conversion service.')}</p>}
    {busy&&<p role="status">{t('تجهيز الملف…','Preparing file…')}</p>}{error&&<p role="alert">{error}</p>}
    <p>{t('لعرض PowerPoint أو Word، افتحه وشارك نافذته، أو صدّره PDF لعرضه هنا. التحويل المباشر إلى صفحات يحتاج خدمة تحويل ملفات.','For PowerPoint or Word, share its window or export it as PDF to present it here. Direct conversion requires a document conversion service.')}</p>
  </section>;
}
