import useAccountName from '../../hooks/useAccountName';
import { Link, useParams } from 'react-router';
import { useLearner } from '../../context/LearnerContext';
import { useLearnerTasks } from '../../context/LearnerTasksContext';
import { usePreferences } from '../../context/PreferencesContext';
import useAccountProfile from '../../hooks/useAccountProfile';
import { getEnrollmentDetails } from '../../data/learnerHelpers';
import { canPreviewCertificate } from '../../data/certificates';
import logo from '../../assets/esham-logo.png';
import '../../styles/certificates.css';
export default function LearnerCertificatesPage(){
 const accountName=useAccountName(); const {courseId}=useParams(),{enrollments}=useLearner(),{tasks}=useLearnerTasks(),{language}=usePreferences(),profile=useAccountProfile();
 const t=(a,e)=>language==='ar'?a:e;const details=enrollments.map(getEnrollmentDetails).filter(Boolean),eligible=details.filter(item=>canPreviewCertificate(item,tasks));const selected=courseId?eligible.find(item=>String(item.courseId)===courseId):null;
 return <main className="learner-dashboard certificate-page"><div className="container"><div className="certificate-tools"><h1>{t('شهاداتي','My certificates')}</h1><p>{t('الشهادة تصدر باسم منصة إسهام وتضم اسم مدرّب الدورة بخط زخرفي يشبه التوقيع.','Certificates are issued by Esham and include the course instructor’s name in a signature-style font.')}</p><p className="learner-demo-label">{t('معاينة تجريبية؛ الاعتماد وتاريخ الإصدار ورقم التحقق تُضاف من الخادم بعد التحقق من الإكمال.','Demo preview; approval, issue date and verification ID require server validation.')}</p><Link to="/learner/progress">{t('العودة إلى التقدّم','Back to progress')}</Link></div>
 {selected ? <><div className="certificate-tools account-actions"><button className="button" onClick={()=>window.print()}>{t('طباعة / حفظ PDF','Print / save PDF')}</button><Link className="button button-outline" to="/learner/certificates">{t('كل الشهادات','All certificates')}</Link></div><article className="esham-certificate" dir={language==='ar'?'rtl':'ltr'} aria-label={t('معاينة شهادة إكمال','Completion certificate preview')}><span className="certificate-watermark">{t('معاينة','PREVIEW')}</span><img src={logo} alt={t('منصة إسهام','Esham platform')}/><p className="certificate-eyebrow">{t('منصة إسهام للتعلّم ومشاركة المعرفة','Esham · Learning & sharing knowledge')}</p><h2>{t('شهادة إكمال دورة','Certificate of completion')}</h2><p>{t('تُقدَّم هذه الشهادة إلى','Presented to')}</p><h3>{profile.name || accountName || t('اسم المتعلّم','Learner name')}</h3><p>{t('لإتمام متطلبات الدورة التدريبية','For completing the requirements of')}</p><h4>{selected.course.title[language]}</h4><div className="certificate-footer"><div><span className="certificate-signature" lang={language}>{selected.course.instructor[language]}</span><span>{t('مدرّب الدورة · توقيع كتابي زخرفي','Course instructor · decorative name signature')}</span></div><div><strong>{t('صادرة عن منصة إسهام','Issued by Esham')}</strong><span>{t('تاريخ الإصدار: بانتظار الاعتماد','Issue date: awaiting approval')}</span><span>{t('الاعتماد ورقم التحقق: بانتظار الربط','Approval & verification ID: not connected')}</span></div></div></article></> : courseId ? <section className="learner-panel"><h2>{t('الشهادة غير متاحة','Certificate unavailable')}</h2><p>{t('يلزم إكمال الدروس واعتماد جميع المهام المطلوبة.','Complete the lessons and obtain approval for all required tasks.')}</p><Link to="/learner/certificates">{t('عرض شهاداتي','View my certificates')}</Link></section> : <section className="learner-panel"><h2>{t('الدورات المستوفية في المعاينة','Eligible courses in this preview')}</h2>{eligible.length?eligible.map(item=><div className="certificate-list-item" key={item.courseId}><div><h3>{item.course.title[language]}</h3><p>{item.course.instructor[language]}</p></div><Link className="button button-outline" to={`/learner/certificates/${item.courseId}`}>{t('معاينة الشهادة','Preview certificate')}</Link></div>):<p>{t('لم تستوفِ دورة شروط الشهادة بعد. ستظهر هنا بعد الإكمال واعتماد المهام.','No course qualifies yet. Certificates appear after completion and task approval.')}</p>}</section>}
 </div></main>;
}
