import { useEffect, useState } from 'react';
import { Link } from 'react-router';
import { courses } from '../../data/courses';
import { readCourseReports, saveCourseReports } from '../../services/courseReports';
import { usePreferences } from '../../context/PreferencesContext';
import CourseSafetyPanel from '../../components/shared/CourseSafetyPanel';
import { categoryAdminUser } from '../../data/categoryAdminDemo';
import '../../styles/community.css';
export default function ModerationQueuePage({scoped=false}){const {language}=usePreferences(),t=(a,e)=>language==='ar'?a:e;const [reports,setReports]=useState(readCourseReports),[status,setStatus]=useState('all'),[selected,setSelected]=useState(null),[resolution,setResolution]=useState(''),[message,setMessage]=useState('');useEffect(()=>{const sync=()=>setReports(readCourseReports());window.addEventListener('esham-course-reports',sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener('esham-course-reports',sync);window.removeEventListener('storage',sync);};},[]);const allowed=course=>!scoped||categoryAdminUser.categoryIds.includes(course.category);const visible=reports.filter(report=>{const course=courses.find(c=>String(c.id)===String(report.courseId));return course&&allowed(course)&&(status==='all'||report.status===status);});const current=reports.find(item=>item.id===selected),course=current&&courses.find(c=>String(c.id)===String(current.courseId));const labels={pending:t('جديد','New'),reviewing:t('قيد التحقيق','Investigating'),resolved:t('تمت المعالجة','Resolved'),dismissed:t('أُغلق دون مخالفة','Dismissed')};function decide(nextStatus){if(!current||!allowed(course)||((nextStatus==='resolved'||nextStatus==='dismissed')&&resolution.trim().length<10)){setMessage(t('أضف نتيجة مراجعة واضحة من عشرة أحرف على الأقل.','Provide a review outcome of at least ten characters.'));return;}const next=reports.map(item=>item.id===current.id?{...item,status:nextStatus,resolution:resolution.trim(),reviewedAt:new Date().toISOString()}:item);if(saveCourseReports(next)){setReports(next);setMessage(t('حُفظت النتيجة المحلية.','Local outcome saved.'));}else setMessage(t('تعذّر الحفظ.','Unable to save.'));}
return <section className="community-page"><h1>{t('بلاغات المحتوى','Content reports')}</h1><p>{t('بلاغات محفوظة على هذا الجهاز للمعاينة؛ صلاحيات الخادم والإشعارات غير مربوطة.','Reports saved on this device for preview; server authorization and notifications are not connected.')}</p><label>{t('حالة البلاغ','Report status')}<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{t('كل الحالات','All statuses')}</option>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><div className="community-grid"><section className="learner-panel"><h2>{t('طابور المراجعة','Review queue')}</h2>{visible.length?visible.map(item=>{const c=courses.find(c=>String(c.id)===String(item.courseId));return <button className="report-list-button" key={item.id} onClick={()=>{setSelected(item.id);setResolution(item.resolution||'');setMessage('');}}><strong>{c.title[language]}</strong><span>{labels[item.status]} · {new Date(item.createdAt).toLocaleDateString(language)}</span></button>}):<p>{t('لا توجد بلاغات بهذه الحالة ضمن صلاحيات المعاينة.','No reports match this status within the preview scope.')}</p>}</section>{current&&course&&allowed(course)&&<section className="learner-panel"><h2>{course.title[language]}</h2><p>{({harmful:t('محتوى مؤذٍ أو خطر','Harmful or dangerous content'),inappropriate:t('محتوى غير ملائم','Inappropriate content'),misleading:t('معلومات مضللة','Misleading information'),copyright:t('حقوق المحتوى','Copyright concern'),other:t('سبب آخر','Other')})[current.reason]}</p><p>{current.description}</p>{current.location&&<p>{current.location}</p>}<Link to={`/courses/${course.id}`}>{t('عرض الدورة','View course')}</Link><label>{t('نتيجة التحقيق','Investigation outcome')}<textarea rows={4} maxLength={2000} value={resolution} onChange={e=>setResolution(e.target.value)}/></label><div className="account-actions"><button className="button" onClick={()=>decide('reviewing')}>{t('بدء التحقيق','Start investigation')}</button><button className="button" onClick={()=>decide('resolved')}>{t('تمت المعالجة','Resolve')}</button><button className="button button-outline" onClick={()=>decide('dismissed')}>{t('إغلاق دون مخالفة','Dismiss')}</button></div>{message&&<p role="status">{message}</p>}<CourseSafetyPanel key={course.id} courseId={`catalog:${course.id}`} administrator/></section>}</div></section>;
}
